language: node_js
node_js:
- '13'
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
env:
  global:
    secure: *********
addons:
  ssh_known_hosts:
  - 120.55.47.104
before_install:
- openssl aes-256-cbc -K $encrypted_04674a2f3de9_key -iv $encrypted_04674a2f3de9_iv
  -in id_rsa.enc -out ~\/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh travis@120.55.47.104 -o StrictHostKeyChecking=no 'cd ~/react-nest-admin/frontend/React-Nest-Admin && git pull && npm install && npm run build'
